/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Can this card hold this roster? Answers before anything loads. */
export declare function plan(totalBytes: number, reservePct: number, declared: any): any
/** A live fleet. Declare once, feed observations, ask for routes. */
export declare class HearthFleet {
  constructor(totalBytes: number, reservePct: number, declared: any)
  setEndpoint(model: string, endpoint: string): void
  /**
   * Record something observed. `kind` is one of:
   * load_started · probe_ok · probe_failed · process_exited · load_failed · stop
   *
   * `gpuPresent` on a probe_failed is the single most important field that
   * crosses this boundary: it is what separates the runtime dropping a model
   * from the host taking the card away. Either spelling is accepted —
   * `gpuPresent` or `gpu_present` — because the mapping now lives in the
   * core, once, instead of once per binding with different key names.
   *
   * Throws on an unrecognised `kind`. It used to return silently, which
   * meant a typo looked exactly like a model that never changed state.
   */
  observe(model: string, kind: string, detail: any, now: number): void
  /** What should a router do with a request for this model? */
  route(model: string, now: number): any
  /**
   * The next model worth bringing up, or null when everything that can be
   * warm already is.
   */
  nextToLoad(): string | null
  committedBytes(): number
  freeBytes(): number
  /**
   * Everything, as one human-readable block. Same text `hearth status`
   * prints, because one truth in two places is how they stop matching.
   */
  report(now: number): string
}
